shell-roboshop

diff --git a/shipping b/shipping
--- a/shipping
+++ b/shipping
@@ -1,84 +1,84 @@
 #!/bin/bash
+
 START_TIME=$(date +%s)
 USERID=$(id -u)
 R="\e[31m"
 G="\e[32m"
 Y="\e[33m"
 N="\e[0m"
-
 LOGS_FOLDER="/var/log/roboshop-logs"
 SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
 LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
 SCRIPT_DIR=$PWD
 
 mkdir -p $LOGS_FOLDER
-echo "Script started execution at: $(date)" | tee -a $LOG_FILE
+echo "Script started executing at: $(date)" | tee -a $LOG_FILE
 
-#check the user has root privileges or not
+# check the user has root priveleges or not
 if [ $USERID -ne 0 ]
-then 
-   echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
-   exit 1 # give other tha 0 upto 127
+then
+    echo -e "$R ERROR:: Please run this script with root access $N" | tee -a $LOG_FILE
+    exit 1 #give other than 0 upto 127
 else
-    echo -e "you are running with root access" |  tee -a $LOG_FILE
-fi 
+    echo "You are running with root access" | tee -a $LOG_FILE
+fi
 
-# validate function takes input as exit status what command they tried to install
+echo "Please enter root password to setup"
+read -s MYSQL_ROOT_PASSWORD
+
+# validate functions takes input as exit status, what command they tried to install
 VALIDATE(){
-if [ $1 -eq 0 ]
-then 
-    echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
-else
-    echo -e "INstalling $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
-    exit 1
-fi 
+    if [ $1 -eq 0 ]
+    then
+        echo -e "$2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
+    else
+        echo -e "$2 is ... $R FAILURE $N" | tee -a $LOG_FILE
+        exit 1
+    fi
 }
 
-echo "please enter root password to setup" 
-read -s MYSQL_ROOT_PASSWORD 
+dnf install maven -y &>>$LOG_FILE
+VALIDATE $? "Installing Maven and Java"
 
-dnf install maven -y &>>$LOG_FILE 
-VALIDATE $? "installing maven and java"
-
-id roboshop 
+id roboshop &>>$LOG_FILE
 if [ $? -ne 0 ]
-then 
-    useradd --system --home /app --shell /sbin/nologin --comment "roboshop system user" roboshop | tee -a $LOG_FILE
-    VALIDATE $? "System user roboshop creating" 
-else 
-    echo -e "roboshop system user already created ... $Y SKIPPING $N" | tee -a $LOG_FILE 
-fi 
+then
+    useradd --system --home /app --shell /sbin/nologin --comment "roboshop system user" roboshop &>>$LOG_FILE
+    VALIDATE $? "Creating roboshop system user"
+else
+    echo -e "System user roboshop already created ... $Y SKIPPING $N"
+fi
 
-mkdir -p /app  &>>$LOG_FILE
-VALIDATE $? "Creating /app directory" 
+mkdir -p /app 
+VALIDATE $? "Creating app directory"
 
-curl -L -o /tmp/shipping.zip https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip | tee -a $LOG_FILE 
-VALIDATE $? "Download shipping code"
+curl -o /tmp/shipping.zip https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip &>>$LOG_FILE
+VALIDATE $? "Downloading shipping"
 
 rm -rf /app/*
 cd /app 
 unzip /tmp/shipping.zip &>>$LOG_FILE
 VALIDATE $? "unzipping shipping"
 
-cd /app 
-mvn clean package  &>>$LOG_FILE 
-VALIDATE $? "packaging the shiping application" 
+mvn clean package  &>>$LOG_FILE
+VALIDATE $? "Packaging the shipping application"
 
-mv target/shipping-1.0.jar shipping.jar &>>$LOG_FILE 
-VALIDATE $? "moving and renaming the jar file" 
+mv target/shipping-1.0.jar shipping.jar  &>>$LOG_FILE
+VALIDATE $? "Moving and renaming Jar file"
 
-cp $SCRIPT_DIR/shipping.service /etc/systemd/system/shipping.service 
-VALIDATE $? "Copying the shipping service" 
+cp $SCRIPT_DIR/shipping.service /etc/systemd/system/shipping.service
 
-systemctl daemon-reload | tee -a $LOG_FILE 
-VALIDATE $? "Daemon reload"
+systemctl daemon-reload &>>$LOG_FILE
+VALIDATE $? "Daemon Realod"
 
-systemctl start shipping | tee -a $LOG_FILE 
-systemctl enable shipping | tee -a $LOG_FILE 
-VALIDATE $? "Starting shipping"
+systemctl enable shipping  &>>$LOG_FILE
+VALIDATE $? "Enabling Shipping"
 
-dnf install mysql -y &>>$LOG_FILE 
-VALIDATE $? "installing mysql"
+systemctl start shipping &>>$LOG_FILE
+VALIDATE $? "Starting Shipping"
+
+dnf install mysql -y  &>>$LOG_FILE
+VALIDATE $? "Install MySQL"
 
 mysql -h mysql.subbuaws.site -u root -p$MYSQL_ROOT_PASSWORD -e 'use cities' &>>$LOG_FILE
 if [ $? -ne 0 ]
@@ -91,18 +91,10 @@ else
     echo -e "Data is already loaded into MySQL ... $Y SKIPPING $N"
 fi
 
-systemctl restart shipping | tee -a $LOG_FILE 
-VALIDATE $? "restarting shipping" 
+systemctl restart shipping &>>$LOG_FILE
+VALIDATE $? "Restart shipping"
 
 END_TIME=$(date +%s)
 TOTAL_TIME=$(( $END_TIME - $START_TIME ))
 
-echo -e "Script executed completed successfully, $Y time taken: $TOTAL_TIME seconds $N" | tee -a $LOG_FILE
-
-
-
-
-
-
-
-
+echo -e "Script exection completed successfully, $Y time taken: $TOTAL_TIME seconds $N" | tee -a $LOG_FILE
